config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /it|en/ do
    root 'pages#home'

    PagesController.action_methods.each do |action|
      get "/#{action}", to: "pages##{action}", as: "#{action}"
    end

    resources :services, only: [:index, :show]
    resources :people  , only: [:index, :show]
    resources :articles, only: :show

    get 'focus/:article_type_id', to: 'article_types#show', as: 'focus'
    get 'focus/:article_type_id/:article_id', to: 'articles#show', as: 'focus_article'

    get :search, to: 'search#index', as: :search
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id              :integer          not null, primary key
#  article_type_id :integer          not null
#  person_id       :integer          not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Article < ApplicationRecord
  translates :title, :description, :text, :slug,
    fallbacks_for_empty_translations: true

  extend FriendlyId

  friendly_id :title, use: :globalize

  globalize_accessors locales: [:it, :en],
                      attributes: [:title, :description, :text, :slug]
  globalize_validations locales: [:it]

  validates :title, :description, :text, :article_type, :person, presence: true
  validates :slug, presence: true, uniqueness: { case_sensitive: false }
  validate :validates_globalized_attributes

  belongs_to :article_type
  belongs_to :person

  scope :published,
    -> { where('created_at <= ?', Time.current) }

  scope :for_site,
    -> { includes(:translations, { person: :translations }) }

  scope :for_admin,
    lambda {
      includes(:translations, { article_type: :translations }).
      order(created_at: :desc)
    }

  before_save :update_slug

  private

  def update_slug
    self.slug_it = title_it.parameterize
    self.slug_en = title_en.parameterize.presence || slug_it
  end
end

app/models/article_type.rb
# == Schema Information
#
# Table name: article_types
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ArticleType < ApplicationRecord
  translates :name, :slug

  globalize_accessors locales: [:it, :en], attributes: [:name, :slug]
  globalize_validations locales: [:it, :en]

  extend FriendlyId

  friendly_id :name, use: :globalize

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: { case_sensitive: false }
  validate :validates_globalized_attributes

  has_many :articles, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:article_id] || params[:id])
    @article_types = ArticleType.includes(:translations)
  end
end

app/views/articles/_article.html.slim
- article_classes = local_assigns[:article_classes]

.masonry-grid__column.masonry-grid__column--1of2
  article.article class=article_classes
    header
      = link_to focus_article_path(article.article_type.slug, article.slug),
                class: 'article__title'
        = article.title
    section
      span> DA
      span.article__author
        = link_to article.person.full_name.upcase,
                  person_path(article.person.slug),
                  class: 'link'
      span
        - time = article.created_at
        = time_tag time, time.strftime('%d %b %Y').upcase
      .article__description
        == article.description

app/views/articles/show.html.slim
- content_for :locale_link, object_locale_path(@article)

- @article_types.each do |article_type|
  = active_link_to article_type.name,
    focus_path(article_type.slug),
    class: 'subtitle subtitle--plain subtitle--indent-right-large subtitle--indent-bottom-middle'

article.article
  header
  h1.title.title--second.title--indent-top-large.title--clipped
    = @article.title
  section
    span> DA
    span.article__author
      = link_to @article.person.full_name.upcase,
                person_path(@article.person.slug),
                class: 'link'
    span
      - time = @article.created_at
      = time_tag time, time.strftime('%d %b %Y').upcase
    .article__description.article__description--indent-top-large
      .columns.columns--gap-large
        == @article.text