config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /it|en/ do
    root 'pages#home'

    PagesController.action_methods.each do |action|
      get "/#{action}", to: "pages##{action}", as: "#{action}"
    end

    resources :services, only: [:index, :show]
    resources :people  , only: [:index, :show]
    resources :articles, only: :show

    get 'focus/:article_type_id', to: 'article_types#show', as: 'focus'
    get 'focus/:article_type_id/:article_id', to: 'articles#show', as: 'focus_article'

    get :search, to: 'search#index', as: :search
  end
end

app/views/pages/contact.html.slim
h1.title.title--first.title--indent-bottom-middle = t 'menu.contact'
.subtitle
  | CG Partners
  br
  | Legal - Governance

br

.grid.grid--gutters-normal
  .grid__cell.grid__cell--1of3.grid__cell--tablet-1of2
    p
      | Milano:
      br
      | Via Morozzo della Rocca, 8
      br
      | 20123 Milano
      br
      | Tel.: +39 02 36742230 / 1
      br
      | Fax: +39 02 86452579
      br
      = link_to 'E-mail:info@chieffi-partners.com',
                'mailto:info@chieffi-partners.com',
                class: 'link'
  .grid__cell.grid__cell--1of3.grid__cell--tablet-1of2
    | Roma:
    br
    | Via Marsala, 29 H
    br
    | 00185 Roma
    br
    | (Stazione Termini)
    br
    = link_to 'E-mail:info@chieffi-partners.com',
              'mailto:info@chieffi-partners.com',
              class: 'link'

app/views/pages/home.html.slim
.grid.grid--gutters-normal.grid--downward
  .grid__cell.grid__cell--2of3
    h2.title.title--first = t('menu.people')
  .grid__cell.grid__cell--1of3.grid__cell--mobile-hidden
    h4.title.title--small CURRICULUM

.grid.grid--gutters-normal
  .grid__cell.grid__cell--2of3
    .columns
      = simple_format t('pages.people.text')
  .grid__cell.grid__cell--1of3.grid__cell--mobile-visible
    h4.title.title--small.title--indent-top-middle CURRICULUM
  .grid__cell.grid__cell--1of3
    - @people.each do |person|
      = link_to person.full_name, person_path(person.slug), class: 'subtitle'
      br

.line

h2.title.title--first.title--indent-bottom-small
  = t('menu.services')

.grid.grid--gutters-large
  - @services_group_by_type.each do |type, services|
    .grid__cell.grid__cell--1of2.grid__cell--indent-bottom
      h4.title.title--small
        = type.name.upcase
      - services.each do |service|
        = link_to service.title, service_path(service.slug), class: 'subtitle'
        br

= link_to t('pages.home.discover'),
          services_path,
          class: 'button button--indented'

- ArticleType.includes(:translations).each do |article_type|
  - if article_type.articles.exists?
    .line

    h2.title.title--first
      = article_type.name.upcase

    .masonry-grid
      = render article_type.articles.published.for_site.limit(4)

    = link_to t('pages.home.see_all'),
              focus_path(article_type.slug),
              class: 'button'

app/views/pages/startup.html.slim
.grid.grid--gutters-normal
  .grid__cell.grid__cell--2of3.grid__cell--tablet-1of1
    h1.title.title--first.title--indent-bottom-middle STARTUP
    .text.text--first
      .columns
        = simple_format t 'pages.startup.text'