config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /it|en/ do
    root 'pages#home'

    PagesController.action_methods.each do |action|
      get "/#{action}", to: "pages##{action}", as: "#{action}"
    end

    resources :services, only: [:index, :show]
    resources :people  , only: [:index, :show]
    resources :articles, only: :show

    get 'focus/:article_type_id', to: 'article_types#show', as: 'focus'
    get 'focus/:article_type_id/:article_id', to: 'articles#show', as: 'focus_article'

    get :search, to: 'search#index', as: :search
  end
end

app/views/layouts/_header.html.slim
header.header
  = link_to '', root_path, class: 'header__logo'
  nav.header__nav
    .header__nav__menu
      = active_link_to t('menu.people'),
                       people_path,
                       class: 'header__nav__menu__link'
      = active_link_to t('menu.services'),
                       services_path,
                       class: 'header__nav__menu__link'
      = active_link_to t('menu.focus'),
                       focus_path('news'),
                       class: 'header__nav__menu__link',
                       active: [['article_types', 'articles'], []]
      = active_link_to t('menu.startup'),
                       startup_path,
                       class: 'header__nav__menu__link'
      = active_link_to t('menu.contact'),
                       contact_path,
                       class: 'header__nav__menu__link'
    = link_to '#search', class: 'header__nav__search', id: 'search'
        .header__nav__search__icon
    = link_to yield(:locale_link).presence || locale_path, class: 'header__nav__language'
      .header__nav__language__value
        = other_locale.upcase
    = link_to '#touch-menu', class: 'header__nav__touch', id: 'touch-menu'
      .header__nav__touch__icon

app/views/layouts/_search.html.slim
.search
  .search__panel
    = form_with url: search_path, method: :get, id: 'search-form' do |form|
      = form.search_field :query,
                          placeholder: t('search'),
                          autocomplete: 'off',
                          autocorrect: 'off',
                          autocapitalize: 'off',
                          spellcheck: 'false',
                          class: 'search__panel__query',
                          id: 'search-query'
  .search__result#search-result
  .search__mask#search-mask
  .search__close#search-close

app/views/layouts/application.html.slim
doctype html
html class="mod-no-js" lang="it"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no"
    title
      | CG Partners
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .page#root
      = render 'layouts/header'
      = render 'layouts/search'
      main
        = yield